spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hackatonsesi}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: UtopiaHikariPool

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

security:
  jwt:
    secret: ${JWT_SECRET:dev-secret-change-me}
    issuer: ${JWT_ISSUER:utopia-hackatonsesi}
    expires-in: ${JWT_EXPIRES_IN_SECONDS:3600}
